### ISSUE TITLE
Explore alternatives to the "big red rectangle"

### ISSUE THREAD

**Issue by dphiffer** [whosonfirst/whosonfirst-www#12]
There's a whole lotta red going on here:
https://whosonfirst.dev.mapzen.com/theory/

I wonder if there's a pleasing photo (or randomly chosen set of photos?) cropped from the blog post corpus that might use the same space nicely?

**Comment by sdombkow** [comment]
Here are a couple of options. The new colors are coming from the style guide. I also looked at the blog posts to see if I could find anything that I thought would fit and that the large majority of images were screenshots from the Spelunker and added that as an option with a little editing. I also wanted to avoid another map to eliminate potential confusion with the home page header or any other interactive map.

![whosonfirstsubpagemock15](https://user-images.githubusercontent.com/1141731/27661253-70337ef8-5c0e-11e7-8f3e-4da99203b729.png)
![whosonfirstsubpagemock14](https://user-images.githubusercontent.com/1141731/27661250-702fe50e-5c0e-11e7-8e0d-b20ee84e2901.png)
![whosonfirstsubpagemock13](https://user-images.githubusercontent.com/1141731/27661251-70312a9a-5c0e-11e7-8717-aab42ea84b64.png)
![whosonfirstsubpagemock12](https://user-images.githubusercontent.com/1141731/27661254-7037b932-5c0e-11e7-85db-58c42d56d8db.png)
![whosonfirstsubpagemock11](https://user-images.githubusercontent.com/1141731/27661252-7033a46e-5c0e-11e7-9586-70cf25cf296e.png)
![whosonfirstsubpagemock10](https://user-images.githubusercontent.com/1141731/27661255-703b407a-5c0e-11e7-9f38-12e5c12c457a.png)

**Comment by thisisaaronland** [comment]
Please no massive colour field paintings :-)

Is the big honking header really necessary? Can we shrink it in a local CSS file?

**Comment by sdombkow** [comment]
Yeah, it could be something like this.

<img width="1680" alt="screen shot 2017-06-28 at 3 20 39 pm" src="https://user-images.githubusercontent.com/1141731/27663081-77232ac2-5c15-11e7-826d-cb7ec94ecd90.png">

**Comment by thisisaaronland** [comment]
Yeah, the last screenshot feels like it is in the same spirit as stuff like: https://mapzen.com/documentation/

**Comment by dphiffer** [comment]
Yeah I like that last one best.
