### ISSUE TITLE
Link to license is broken

### ISSUE THREAD

**Issue by justinclift** [whosonfirst/whosonfirst-www#30]
Going to the SQLite page here:

&nbsp; &nbsp; https://whosonfirst.mapzen.com/sqlite/

At the bottom there are several links.  The "licensing" one is broken, giving 404 when clicked on:

```
https://whosonfirst.mapzen.com/docs/licensing/
• Code: NoSuchKey
• Message: The specified key does not exist.
• Key: docs/licensing/index.html
• RequestId: 92BAB3FAC89E060E
• HostId: vG1De2bRy2EWkY3WdsOvY+RYJFSS9LqJBNKup2ucefJPcioRLaBZ65CNJSrorkBPyOHxdCpKchs=
```

Note - I'm not entirely sure I'm reporting this issue against the correct GitHub repo for the website.  If I'm wrong, I'm happy to redo it elsewhere. :smile:

**Comment by thisisaaronland** [comment]
Thanks for this. We'll fix it shortly.

**Comment by justinclift** [comment]
Hmmm, something seems wrong with the website in general now.

Trying to visit it gives a CloudFront error, saying the domain has been misconfigured.

Known problem?

**Comment by thisisaaronland** [comment]
All the WOF stuff (including the license info) has moved to `whosonfirst.org`:
 
https://whosonfirst.org/docs/licenses/

https://whosonfirst.org/blog/2018/01/02/chapter-two/

**Comment by justinclift** [comment]
Awesome.

As a data point, that new licenses page has a (broken) link to the old mapzen website in the "See Also" section of the page.  Probably should be removed. :smile:

**Comment by justinclift** [comment]
Ahhh, reading that blog entry it sounds like things have massively scaled down.

If any of your dev team are German, then the Prototype fund might be interesting to fund things again for a while:

&nbsp; &nbsp; https://prototypefund.de/en/

**Comment by nvkelso** [comment]
@justinclift Thanks for the tip!
