### ISSUE TITLE
Generate /docs/licenses from whosonfirst-sources

### ISSUE THREAD

**Issue by straup** [whosonfirst/whosonfirst-www#49]
https://github.com/whosonfirst/whosonfirst-sources/tree/master/sources
https://github.com/whosonfirst/whosonfirst-sources#source-properties

Also, use this as a test-drive for fetching/rendering questions in https://github.com/whosonfirst/whosonfirst-www/milestone/3

**Comment by stepps00** [comment]
I think this was completed through https://github.com/whosonfirst/whosonfirst-www/pull/71.. are we okay to close this issue?

**Comment by nvkelso** [comment]
Yep!
