### ISSUE TITLE
Update sources page with current source list

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www#67]
https://whosonfirst.org/docs/sources/list/

This page is out of date, last updated 2017-08-25. Let's update the page to point to the most recent list of sources, here:

https://github.com/whosonfirst/whosonfirst-sources/blob/master/sources/README.md

Looks like the sources list is coming from this page:

https://github.com/whosonfirst/whosonfirst-www/blob/master/www/docs/sources/listofsources.html

**Comment by nvkelso** [comment]
This is important, let's move on it please.

**Comment by nvkelso** [comment]
Related? https://github.com/whosonfirst/whosonfirst-www/issues/49

**Comment by nvkelso** [comment]
The CSS styling on the page is also janky (no left margin)

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst/whosonfirst-www/commit/bfb9b19cdd08b3c47ea78b58f629f3eae000eae0

```
make docs-download-sources
make docs-build-pages
make local
make sync
```

Related: 

* https://github.com/whosonfirst/whosonfirst-www#important
* https://github.com/whosonfirst/whosonfirst-www/issues/68

**Comment by stepps00** [comment]
Thanks @thisisaaronland ! I now see the same as-of date and source count when comparing the whosonfirst.org sources list with the sources list on the sources Github page.

Going forward, I'll mimic the `make` steps to keep the page updated.
