### ISSUE TITLE
Blog post about megacity work

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-www#75]
https://github.com/whosonfirst-data/whosonfirst-data/issues/1547

This issue was recently completed.. it would be a good candidate for a blog post.

**Comment by thisisaaronland** [comment]
Yes please!

Does this mean we have geometries for all of these now? If so they would make good candidates for a subsequent blog post about the `go-whosonsfirst-spatial` PIP stuff.

**Comment by stepps00** [comment]
> Does this mean we have geometries for all of these now?

Yep, the work we've done includes:

- Unflagging some records that incorrectly had a `wof:megacity` property set
- Flagging records that didn't have a `wof:megacity` property, but needed one (based on the NE populated places file)
- Adding polygon geometries to all megacity records (some had point geometries)
- Updating some zoom levels / concordances to NE, when possible

I tried to use parent geometries (mostly `meso`) to construct new locality polygons, but some were digitized by hand.

**Comment by thisisaaronland** [comment]
Nice. I am considering adding very basic query functionality to the `go-whosonfirst-index` package(s). Something along the lines of:

https://github.com/aaronland/go-smithsonian-openaccess#inline-queries

That, when exposed via the CLI properties to the `go-whosonfirst-dist` packages would allow you to build SQLite distributions, for example, with spatial indexes for all the megacities across (n) repos.

That's as far as I've gotten with the idea though...

**Comment by stepps00** [comment]
> That, when exposed via the CLI properties to the go-whosonfirst-dist packages would allow you to build SQLite distributions, for example, with spatial indexes for all the megacities across (n) repos.

Very cool.. sounds like this could be used to create per-placetype dist files? All neighbourhoods, counties, etc?

**Comment by thisisaaronland** [comment]
Now that you mention it, yes. That would make what you're describing possible.

**Comment by stepps00** [comment]
Just following up here.. I've got a draft blog post locally. I'll likely push to a branch this weekend.
